# Generated by Django 5.0.3 on 2024-03-08 08:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 9, 57, 43, 67314), editable=False)),
                ('Nom_Adherateur', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('telephone', models.CharField(blank=True, max_length=13, null=True)),
                ('motivation', models.TextField(null=True)),
                ('ville', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 9, 57, 43, 66315), editable=False)),
                ('NomDonneur', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=13, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('montant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('Tag', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagePost')),
                ('contenu', models.TextField(blank=True)),
                ('blogPoster', models.CharField(blank=True, max_length=128)),
                ('joinPiece', models.FileField(blank=True, null=True, upload_to='')),
                ('joinLink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Volontariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Volontaire', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('telephone', models.CharField(max_length=13)),
                ('motivation', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('ville', models.CharField(max_length=250)),
                ('activite', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('date', models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 9, 57, 43, 65314), editable=False)),
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADPC_APP.post')),
            ],
        ),
    ]
