# Generated by Django 5.0.3 on 2024-03-08 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADPC_APP', '0004_alter_adhesion_date_alter_commentaire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('lien', models.URLField(default='#')),
                ('photo', models.ImageField(upload_to='imagePartners')),
            ],
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 10, 51, 3, 821344), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 10, 51, 3, 819345), editable=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 10, 51, 3, 820345), editable=False),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='photo',
            field=models.ImageField(upload_to='imageSouvenirs'),
        ),
    ]
