# Generated by Django 5.0.3 on 2024-03-08 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADPC_APP', '0005_partenaire_alter_adhesion_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=500)),
                ('lieu', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('autre', models.CharField(max_length=500)),
                ('web', models.CharField(max_length=500)),
                ('qui_sommes_nous', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mot_president',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('sous_titre', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
                ('signature', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='imagePresi')),
            ],
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 21, 13, 28, 153292), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 21, 13, 28, 151300), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 8, 21, 13, 28, 152293), editable=False),
        ),
    ]
