# Generated by Django 5.0.3 on 2024-03-09 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADPC_APP', '0006_informations_mot_president_alter_adhesion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 16, 22, 24, 970866), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 16, 22, 24, 969840), editable=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='NomDonneur',
            field=models.CharField(default='Inconnu', max_length=250),
        ),
        migrations.AlterField(
            model_name='don',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 16, 22, 24, 970866), editable=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='motivation',
            field=models.TextField(blank=True, default='Inconnu', null=True),
        ),
        migrations.AlterField(
            model_name='don',
            name='telephone',
            field=models.CharField(default='Inconnu', max_length=13),
        ),
    ]
