# Generated by Django 5.0.3 on 2024-03-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADPC_APP', '0013_alter_adhesion_date_alter_commentaire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 16, 51, 55, 55870), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 16, 51, 55, 50112), editable=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='NomDonneur',
            field=models.CharField(auto_created=True, blank=True, default='Un Inconnu', max_length=250),
        ),
        migrations.AlterField(
            model_name='don',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 16, 51, 55, 53117), editable=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='motivation',
            field=models.TextField(auto_created=True, blank=True, default='Inconnue'),
        ),
        migrations.AlterField(
            model_name='don',
            name='telephone',
            field=models.CharField(auto_created=True, blank=True, default='Inconnu', max_length=13),
        ),
    ]
