# Generated by Django 5.0.3 on 2024-03-09 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADPC_APP', '0017_alter_adhesion_date_alter_commentaire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='Proffession',
            field=models.CharField(default='Aucune', max_length=250),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 18, 44, 2, 80119), editable=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 18, 44, 2, 75807), editable=False),
        ),
        migrations.AlterField(
            model_name='don',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 9, 18, 44, 2, 76820), editable=False),
        ),
    ]
